print("Hello World!, 7")
print(7 + 3)
print(7 - 3)
print(7 * 3)
print(7 / 3)
print(7 // 3)
print(7 % 3)
print(7 ** 3)
print(3 * (3 + 3) / 3 - 3)
print("Hello" + " " + "World!")
print("Hello" + " " + "World!" + " " + str(7))
print("Hello" + " " + "World!" + " " + str(7 + 3))
print("Bye")